#!/bin/bash

if ! command -v git>/dev/null 2>&1;then
    echo "git is not installed!">&2
    exit 1
fi

gitconfig(){
    git config --global user.email "$1"
    git config --global user.name "$2"
    git config --global http.postBuffer 524288000
    git config --global push.default simple
    #save password for several minutes
    git config --global credential.helper cache
    git config --global alias.tree "log --oneline --graph --decorate --all"
    if command -v vim >/dev/null 2>&1;then
        git config --global core.editor vim
    fi
    if command -v vimdiff >/dev/null 2>&1;then
        git config --global diff.tool vimdiff
    fi

    read -p "Set git proxy ?[Y/n] " gitp
    if [[ "$gitp" != [nN] ]];then
        # git config --global http.proxy "http://127.0.0.1:8118"
        # git config --global https.proxy "http://127.0.0.1:8118"
        echo "set git http.proxy to socks5://localhost:1080"
        echo "set git https.proxy to socks5://localhost:1080"
        git config --global http.proxy "socks5://localhost:1080"
        git config --global https.proxy "socks5://localhost:1080"
    fi
}

read -p "git user.email: (default: sunliang711@163.com)" -t 5 email
read -p "git user.name: (default: sunliang)" -t 5 name
if [[ -z "$email" ]];then
    email="sunliang711@163.com"
fi
if [[ -z "$name" ]];then
    name="sunliang"
fi
gitconfig "$email" "$name"

#vim setf sh
