CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(XXX)

SET(CMAKE_BUILD_TYPE DEBUG)
SET(CMAKE_CXX_FLAGS -std=c++0x)

#PROJECT_BINARY_DIR is builder dir
SET(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/lib)
SET(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)

#add_subdirectory(xxx)
#include_directories(xxx)

#FIND_PACKAGE(Boost 1.60 REQUIRED COMPONENTS system ...)
#INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})

AUX_SOURCE_DIRECTORY(. SOURCES)

ADD_EXECUTABLE(${PROJECT_NAME} ${SOURCES})
#TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${Boost_LIBRARIES})
ADD_CUSTOM_TARGET(clean-all
rm -rf *
)
#make clean-all
