#!/bin/bash
if ! command -v apt-get >/dev/null 2>&1;then
    echo "Error: Not ubuntu!"
    exit 1
fi
if [[ $EUID != 0 ]];then
    echo "Error:need root priviledge!"
    exit 1
fi

#设置ubuntu国内源
if grep -i 'ubuntu' /etc/issue >/dev/null 2>&1;then
    read -p "Use Chinese software source ? [y/N] " -t 5 soft
    if [[ "$soft" == [yY] ]];then
        bash ./ubuntu-china-source
    fi
fi

installer=apt-get

#apt比apt-get更好用
if command -v apt > /dev/null 2>&1;then
    installer=apt
fi

basicApps="vim vim-gtk tree curl screenfetch zsh"
devApps="linux-headers-generic build-essential cmake clang  python-apt python-dev python-pip python3-dev python3-pip libboost-all-dev golang golang-golang-x-tools ncurses-dev"
inputApps="fcitx fcitx-sunpinyin fcitx-table-wubi"

$installer update -y
read -p "Install development tools (ie:clang python golang)? [Y/n] " -t 3 installDev
read -p "Install fcitx input method? [y/N] " -t 3 installFcitx
for app in ${basicApps};do
    $installer install $app -y
done

if [[ "$installDev" != [nN] ]];then
    for app in ${devApps};do
        $installer install $app -y
    done
fi

if [[ "$installFcitx" == [yY] ]];then
    for tool in ${inputApps};do
        $installer install $tool -y
    done
fi
