#!/bin/bash
checkCmd(){
    if (($#>0));then
        if ! command -v $1 >/dev/null 2>&1;then
            echo "Need cmd: $1"
            exit 1
        fi
    fi
}

help(){
    echo "Usage: $(basename $0) OPTIONS vim/nvim"
    echo "OPTIONS:"
    echo -e "\t\t-p Using socks5://localhost:1080 proxy"
    echo -e "\t\t-g for vim-go"
    echo -e "\t\t-y for YouCompleteMe"
}

installDependence(){
    #arch
    if command -v pacman >/dev/null 2>&1;then
        archApps="linux-headers clang neovim vim cmake python boost python-pip go go-tools fontconfig ctags "
        echo "pacman update..."
        sudo pacman -Syu --noconfirm >/dev/null 2>&1
        for tool in ${archApps};do
            echo "Install $tool..."
            sudo pacman -S $tool --noconfirm --needed >/dev/null 2>&1
        done
    fi

    #fedora
    if command -v dnf >/dev/null 2>&1;then
        fedoraApps="kernel-devel vim clang python-devel python-pip python3-devel python3-pip cmake golang golang-godoc boost-devel ncurses-devel "
        echo "dnf update..."
        sudo dnf update -y >/dev/null 2>&1
        echo "dnf install dev tools..."
        sudo dnf groupinstall "development tools" -y >/dev/null 2>&1
        for tool in ${fedoraApps};do
            echo "Install $tool..."
            sudo dnf install $tool -y >/dev/null 2>&1
        done
    fi

    #ubuntu
    if command -v apt-get >/dev/null 2>&1;then
        ubuntuApps="build-essential linux-headers-generic vim vim-gtk cmake clang python-apt python-dev python-pip python3-dev python3-pip libboost-all-dev golang golang-golang-x-tools ncurses-dev "
        echo "apt-get update..."
        sudo apt-get update -y >/dev/null 2>&1
        for tool in ${ubuntuApps};do
            echo "Install $tool..."
            sudo apt-get install $tool -y >/dev/null 2>&1
        done
    fi
}


#安装airline需要用的字体
installFont(){
    case $(uname) in
        "Linux")
            if fc-list | grep -iq Powerline;then
                return
            fi

            if [ ! -d ~/.local/share/fonts ];then
                mkdir -pv ~/.local/share/fonts
            fi
            cp ./fonts/PowerlineSymbols.otf ~/.local/share/fonts
            cp ./fonts/Droid\ Sans\ Mono\ for\ Powerline\ Nerd\ Font\ Complete.otf ~/.local/share/fonts
            fc-cache -vf ~/.local/share/fonts

            if [ ! -d ~/.config/fontconfig/conf.d ];then
                mkdir -pv ~/.config/fontconfig/conf.d
            fi
            cp ./fonts/10-powerline-symbols.conf ~/.config/fontconfig/conf.d
            ;;
        "Darwin")
            command -v brew >/dev/null 2>&1 || { echo "Need install homebrew first!"; exit 1; }
            if [ -n "$proxy" ];then
                ALL_PROXY=$proxy brew tap caskroom/fonts
                ALL_PROXY=$proxy brew cask install font-hack-nerd-font
            else
                brew tap caskroom/fonts
                brew cask install font-hack-nerd-font
            fi
            echo "set Knack nerd font in iterm"
            ;;
        MINGW32*)
            echo "Please install nerd font manually."
            ;;
        *)
            echo "Unknown OS,install font failed!" >& 2
            ;;
    esac
}

installBasic(){
    checkCmd curl
    installDependence
    installFont

    uninstall

    mkdir -pv $root/autoload
    mkdir -pv $root/plugins

    #copy color scheme
    cp -r colors $root
    #copy ftplugin
    cp -r ftplugin $root

    msg  "Downloading vim-plug from github..."
    $CURL -fLo $root/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim || { echo "download vim-plug failed.";uninstall; exit 1; }

    if [[ "$whichVim" == "nvim" ]];then
        if [ -n "$proxy" ];then
            echo "Using proxy 127.0.0.1:8118 to install pip and neovim"
            sudo -H pip --proxy 127.0.0.1:8118 install --upgrade pip || { echo "pip install failed."; uninstall; exit 1; }
            sudo -H pip --proxy 127.0.0.1:8118 install --upgrade neovim || { echo "pip install neovim failed."; uninstall; exit 1; }
        else
            sudo -H -E pip install --upgrade pip
            sudo -H -E pip install --upgrade neovim
        fi
    fi

    cp  init.vim $cfg
    $whichVim +PlugInstall +qall
}

uninstall(){
    rm -rf $root
    rm -f $cfg
}
