#!/bin/bash
#ROOT是变量，在安装的时候会被替换
db=ROOT/db

iptables -t filter -P INPUT DROP
iptables -t filter -P OUTPUT ACCEPT
iptables -t filter -P FORWARD ACCEPT
iptables -t filter -F

#从portConfig数据表中读取
enabledPorts=$(sqlite3 "$db" "select type,port from portConfig where enabled=1;")
#debug
echo "enabledPorts: $enabledPorts"

if [ -n "$enabledPorts" ];then
    echo "$enabledPorts" | while read record;do
        type=$(echo $record | awk -F'|' '{print $1}')
        port=$(echo $record | awk -F'|' '{print $2}')
        #debug
        echo "type: $type"
        echo "port: $port"
        cmd="iptables -t filter -A INPUT -p $type -m $type --dport $port -j ACCEPT"
        #为了监控从这个端口的输出流量
        outputcmd="iptables -t filter -A OUTPUT -p $type --sport $port"
        bash -c "$outputcmd"
        bash -c "$cmd"
    done
fi
