
RUN echo 'deb http://mirrors.163.com/debian/ jessie main non-free contrib'>/etc/apt/sources.list
RUN echo 'deb http://mirrors.163.com/debian/ jessie-updates main non-free contrib'>>/etc/apt/sources.list
RUN echo 'deb http://mirrors.163.com/debian/ jessie-backports main non-free contrib'>>/etc/apt/sources.list
RUN echo 'deb-src http://mirrors.163.com/debian/ jessie main non-free contrib'>>/etc/apt/sources.list
RUN echo 'deb-src http://mirrors.163.com/debian/ jessie-updates main non-free contrib'>>/etc/apt/sources.list
RUN echo 'deb-src http://mirrors.163.com/debian/ jessie-backports main non-free contrib'>>/etc/apt/sources.list
RUN echo 'deb http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib'>>/etc/apt/sources.list
RUN echo 'deb-src http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib'>>/etc/apt/sources.list
RUN apt-get update
